

-- ----------------------------------------------
-- DDL Statements for tables
-- ----------------------------------------------

CREATE TABLE "CUSTOMERS" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "CUSTOMER_NAME" VARCHAR(255), EMAIL VARCHAR(255), PASSWORD VARCHAR(255));

CREATE TABLE "EVENTS" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "EVENT_NAME" VARCHAR(255), "DESCRIPTION" VARCHAR(1000), "EVENT_DATE" VARCHAR(255), "LOCATION" VARCHAR(255), "MAX_CAPACITY" INTEGER, "CURRENT_REGISTRATIONS" INTEGER DEFAULT 0);

CREATE TABLE "REGISTRATIONS" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "CUSTOMER_ID" INTEGER, "EVENT_ID" INTEGER, "REGISTRATION_DATE" VARCHAR(255), "STATUS" VARCHAR(50) DEFAULT 'ACTIVE');

-- ----------------------------------------------
-- DDL Statements for keys
-- ----------------------------------------------

-- primary/unique
ALTER TABLE "CUSTOMERS" ADD CONSTRAINT "SQL120325130144011" PRIMARY KEY ("ID");
ALTER TABLE "EVENTS" ADD CONSTRAINT "PK_EVENTS" PRIMARY KEY ("ID");
ALTER TABLE "REGISTRATIONS" ADD CONSTRAINT "PK_REGISTRATIONS" PRIMARY KEY ("ID");

-- foreign keys
ALTER TABLE "REGISTRATIONS" ADD CONSTRAINT "FK_REG_CUSTOMER" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "CUSTOMERS"("ID");
ALTER TABLE "REGISTRATIONS" ADD CONSTRAINT "FK_REG_EVENT" FOREIGN KEY ("EVENT_ID") REFERENCES "EVENTS"("ID");

